#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/chris.torstenson/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export VISUAL=vim
export EDITOR="$VISUAL"

# path
export PATH=$PATH:$HOME/.composer/vendor/bin
export PATH="$PATH:~/scripts"

# aliases
alias gl="git log --oneline"
alias gd="git diff"
alias gs="git status"
alias gb="git branch"

# navigation
alias ck='cd ~/ck_repos/cs'
alias ll='ls -laxohG'
alias l='ls -G'

# git
# alias gfi='git'
# alias gp='git pull'
alias ga='git add'
alias gaa='git add --a'
alias gau='git add -u'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gf='git fetch && git branch -a'
alias gp='git pull'
alias gpd='find . -type d -depth 1 -exec git --git-dir={}/.git --work-tree=$PWD/{} pull origin master \;'
alias gpush='git push -u origin HEAD'
alias gs='git status'

# grep
alias grep='grep --color=tty'
alias fgrep='fgrep --color=tty'
alias egrep='egrep --color=tty'

# refresh shell
alias reload='source ~/.zshrc'

# apps
alias mark='open -a Marked\ 2.app'

# other
alias ctags="`brew --prefix`/bin/ctags"

source ~/.nvm/nvm.sh # load nvm

# host toggle
function set_hosts {
    sudo cp /etc/hosts-backup/hosts.dev /etc/hosts
}

function unset_hosts {
    sudo cp /etc/hosts-backup/hosts.nodev /etc/hosts
}

autoload -Uz promptinit
promptinit
prompt steeef
